[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="light"
primaryColor="#0099ff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"
